### ISSUE TITLE
[Major, Conversation] The chat is not listed according to the time

### ISSUE THREAD

**Issue by carmenlau** [skygear-demo/SkygearChat-iOS-Demo#35]
Need check again if get conversation api have any sort by option. Should sort by last message sent time desc.

![img_3561](https://user-images.githubusercontent.com/388892/37379889-da41670a-2770-11e8-956d-38a70ddbbcfb.png)

**Comment by ben181231** [comment]
This issue to be fix after [the PR](https://github.com/SkygearIO/chat/pull/206) is merged.

**Comment by carmenlau** [comment]
Updated at https://github.com/SkygearIO/chat/commit/7ae728c3e5ce18b09a2368a2c925a587bc448ff5
