### ISSUE TITLE
Message in wrong conversation room / under wong username

### ISSUE THREAD

**Issue by mayyuen318** [skygear-demo/SkygearChat-iOS-Demo#8]
<img width="283" alt="screen shot 2017-10-16 at 12 27 25 pm" src="https://user-images.githubusercontent.com/7130966/31595339-9b3b089a-b26d-11e7-8cd9-1d18787089ea.png">

I was trying to test with user Ten but our conversation is shown in my own username conversation.

**Comment by tszkanlo** [comment]
Cause: the title showing is the conversation title. the conversation title is by default the username selected when the conversation is created
Fix: fetch the username when direct conversation
